# Generated by Django 3.1.6 on 2021-07-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=15)),
                ('taille', models.CharField(max_length=10)),
                ('caracterisk', models.CharField(choices=[('Am', 'Avec manche'), ('Sm', 'Sans manche')], default='Sm', max_length=2)),
                ('specifik', models.CharField(choices=[('Ad', 'Avec design'), ('Sd', 'Sans design')], default='Sd', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CustomersContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=25)),
                ('tname', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('picture', models.ImageField(upload_to='img/%y')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customerscontact')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
