# Generated by Django 3.1.6 on 2021-07-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.TextField(default='ma description'),
            preserve_default=False,
        ),
    ]
