# Generated by Django 2.2.14 on 2021-08-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_pricecatalogue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceCatalogue',
        ),
    ]
