# Generated by Django 2.2.14 on 2021-08-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210804_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='commands',
            options={'verbose_name': 'Commande'},
        ),
        migrations.AlterModelOptions(
            name='customerscontact',
            options={'verbose_name': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit'},
        ),
        migrations.RemoveField(
            model_name='categories',
            name='caracterisk',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='specifik',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='categories',
            name='price',
            field=models.FloatField(default=0, verbose_name='Prix'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='caracterisk',
            field=models.CharField(choices=[('Am', 'Avec manche'), ('Sm', 'Sans manche')], default='Sm', max_length=2, verbose_name='Caracteristique'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifik',
            field=models.CharField(choices=[('Ad', 'Avec design'), ('Sd', 'Sans design')], default='Sd', max_length=2, verbose_name='Specificité'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='reference',
            field=models.CharField(max_length=15, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='taille',
            field=models.CharField(max_length=10, verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='contacted',
            field=models.BooleanField(default=False, verbose_name='Demande traitée ?'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoie"),
        ),
        migrations.AlterField(
            model_name='customerscontact',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customerscontact',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de Creation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='img/%y', verbose_name='Image'),
        ),
    ]
