# Generated by Django 2.2.14 on 2021-08-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210805_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='reference',
            field=models.CharField(max_length=30, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='taille',
            field=models.CharField(max_length=100, verbose_name='Taille'),
        ),
    ]
