# Generated by Django 2.2.14 on 2021-08-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210805_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='quantity',
        ),
        migrations.AddField(
            model_name='categories',
            name='pack_quantity',
            field=models.IntegerField(default=0, verbose_name='Quantité par pack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='piece_quantity',
            field=models.IntegerField(default=0, verbose_name='Quantité par piece'),
            preserve_default=False,
        ),
    ]
